### ISSUE TITLE
Adding libbearssl.a to Arduino

### ISSUE THREAD

**Issue by kaushal1214** [earlephilhower/bearssl-esp8266#6]
I'm trying to sign the .bin of esp8266 for secure OTA updates. I'm stuck with the code `BearSSL:PubliKey` as it is not getting recognized, although I have already copied the `libbearssl.a` in `~/Arduino/libraries` directory. Is this the correct path? I also tried `Arduinobearssl` library but I guess it only works for arduino boards, or is it the same library? I'm new to this, please help.

**Comment by devyte** [comment]
If you want to sign the bin, why did you copy the .a? Did you readthedocs? There's a section dedicated to this.

**Comment by earlephilhower** [comment]
This is not related to the actual library.  See the 8266 Arduino docs and example for the signing use.

**Comment by kaushal1214** [comment]
Thank you for taking out your time to reply back. And sorry, I forgot to add the document link that I am following, here- `https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html`. 
In the document, it's mentioned that we can sign the bin in two ways using arduino IDE- 
1. Automatic signing
2. Manual signing binaries

First one didn't work for me so I'm trying the second one. In the `Manual Signing Binaries` section, few lines of code is given, which can create a `BearSSL` public key, a `SHA256` hash verifier, and tells the Update object to use them to validate any updates it receives from any method.
The code:
#### <in globals>BearSSL::PublicKey signPubKey( ... key contents ... );  
#### BearSSL::HashSHA256 hash; 
#### BearSSL::SigningVerifier sign( &signPubKey );
#### ...
#### <in setup()>
#### Update.installSignature( &hash, &sign );
